### PR TITLE
skip reading unused columns

### PR DESCRIPTION
**Pull request by richox**
closes https://github.com/datafusion-contrib/datafusion-orc/issues/132 .

### CODE REVIEW

**Review by waynexia — APPROVED** [review]
LGTM. PTAL @WenyXu

**Comment by waynexia** [comment]
Thanks for reporting and fixing this issue @richox :heart:

**Review by Xuanwo — APPROVED** [review]
Thank @richox for fixing this, and thank you @waynexia for the review.

The only thing left is fixing our CI.

**Review by WenyXu — APPROVED** [review]
LGTM, thanks!

**Comment by WenyXu** [comment]
The coverage test is failed😞

**Comment by richox** [comment]
> The coverage test is failed😞

fixed, we need to also read all children columns of nested types.

**Comment by WenyXu** [comment]
> > The coverage test is failed😞
> 
> fixed, we need to also read all children columns of nested types.

Thanks ❤️ @richox

**Pull request merged**
