### PR TITLE
Crate for generating proto.rs from orc_proto.proto

### PR DESCRIPTION
**Pull request by Jefffrey**

### CODE REVIEW

**Comment by WenyXu** [comment]
How about generating the file in build.rs? Such as [this example](https://github.com/danburkert/snazzy/blob/master/build.rs)

**Comment by Jefffrey** [comment]
> How about generating the file in build.rs? Such as [this example](https://github.com/danburkert/snazzy/blob/master/build.rs)

Yeah I did consider this initially, but I decided to follow the pattern set by [arrow-flight](https://github.com/apache/arrow-rs/tree/master/arrow-flight) as the proto file wouldn't often change

**Review by waynexia — APPROVED** [review]
Would it update the generated files automatically?

**Comment by Jefffrey** [comment]
> Would it update the generated files automatically?

We'll need to run the regen.sh manually whenever we put in updated proto file

Probably wouldn't happen too often

**Comment by waynexia** [comment]
Okay.

I'm going to ignore the failed CI due most of changes are generated

**Pull request merged**
