### PR TITLE
fix: execute "select count(*) from tbl" always getting zero

### PR DESCRIPTION
**Pull request by harveyyue**
Fix: #113

### CODE REVIEW

**Comment by WenyXu** [comment]
Please run the `make fmt`

**Comment by harveyyue** [comment]
> Please run the `make fmt`

Done.

**Comment by WenyXu** [comment]
@waynexia PTAL

**Comment by waynexia** [comment]
This seems to be an unexpected behavior of empty projection. This fix doesn't solves the root cause but it works anyway. I'm ok to merge it. Thanks @harveyyue 

BTW, I just came across this だからもっと from @Jefffrey 😆 
image

**Pull request merged**
