### PR TITLE
Pass target arrow type to array_decoder_factory

### PR DESCRIPTION
**Pull request by progval**
This is the prerequisite to support configurable timestamp precision mentioned in https://github.com/datafusion-contrib/datafusion-orc/issues/75#issuecomment-2130754391

### CODE REVIEW

**Review by waynexia — APPROVED** [review]
Thanks @progval, this API looks good to me overall 👍 

One thing I'm concerning is we may also need to provide a method that can convert ORC type to Arrow type, the so-called "default" option (or there is one and I miss it?). Otherwise the external user of `array_decoder_factory` needs to maintain that mapping by themselves.

**Comment by progval** [comment]
> One thing I'm concerning is we may also need to provide a method that can convert ORC type to Arrow type, the so-called "default" option (or there is one and I miss it?). Otherwise the external user of array_decoder_factory needs to maintain that mapping by themselves.

Yes, I'm planning to add it after #93 is merged. Probably `.with_default_time_unit(TimeUnit)` or `.with_default_timestamp_type::<T: arrow::datatypes::ArrowTimestampType>()` on the reader builder

**Review by Jefffrey — COMMENTED** [review]
Do you think it's possible to store the `Field` inside `Column` itself, considering it's already storing `DataType`?

https://github.com/datafusion-contrib/datafusion-orc/blob/ac5a8ab29e0fb43629ca93ffff1e722412418b36/src/column.rs#L15-L21

Might cut down on having to pass field everywhere :thinking:

**Review by Jefffrey — APPROVED** [review]
Thanks for this, and thanks for the detailed breakdown on my suggestion :heart:

**Pull request merged**
