### PR TITLE
refactor: refactor byte/boolean iter

### PR DESCRIPTION
**Pull request by WenyXu**
I'm trying to implement the list datatype. However, I found that our present iterator relies on the `number_of_rows` of stripe, which made the nested lists also rely on it.

### CODE REVIEW

**Review by Jefffrey — COMMENTED** [review]
How does boolean iter work here if the no. of elements encoded within isn't a multiple of 8? Is there a check somewhere else?

**Comment by WenyXu** [comment]
> How does boolean iter work here if the no. of elements encoded within isn't a multiple of 8? Is there a check somewhere else?

It reads the next byte until it reaches the end of the buffer.

**Comment by Jefffrey** [comment]
> > How does boolean iter work here if the no. of elements encoded within isn't a multiple of 8? Is there a check somewhere else?
> 
> It reads the next byte until it reaches the end of the buffer.

So it'll emit extra false values for the padding bits that the caller will have to deal with, e.g. via `take()`?

**Comment by WenyXu** [comment]
> > > How does boolean iter work here if the no. of elements encoded within isn't a multiple of 8? Is there a check somewhere else?
> > 
> > 
> > It reads the next byte until it reaches the end of the buffer.
> 
> So it'll emit extra false values for the padding bits that the caller will have to deal with, e.g. via `take()`?

Yes, The caller only calls `next` with the exact no. of rows times.

**Review by Jefffrey — APPROVED** [review]

**Pull request merged**
